version: 2 

sources:
  - name: citibike_raw
    tables:
      - name: trips
        config:
          external_location: "read_parquet('../data/bronze/year=*/month=*/trips.parquet')"

  - name: weather_raw
    tables:
      - name: daily_weather
        config:
          external_location: "read_parquet('../data/bronze/weather/daily_weather.parquet')"