version: 2 

models:
  - name: stg_citibike_trips
    description: Cleaned citi bikes trips from raw parquet files.
    columns:
      - name: ride_id
        tests:
          - not_null
          - unique 
      
      - name: started_at
        tests:
          - not_null

      - name: ended_at 
        tests:
          - not_null

      - name : member_casual 
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['member', 'casual']